<?php
return array(
	'panelTest' => array(
		'type' => 0,
		'description' => 'Доступ к панели тестирования',
		'bizRule' => null,
		'data' => null,
	),
	'changeOwnRoleTest' => array(
		'type' => 0,
		'description' => 'Изменение собственной роли',
		'bizRule' => null,
		'data' => null,
	),
	'changeUserIdTest' => array(
		'type' => 0,
		'description' => 'Действовать от лица пользователя',
		'bizRule' => null,
		'data' => null,
	),
	'reinstallRbacTest' => array(
		'type' => 0,
		'description' => 'Переустановить RBAC',
		'bizRule' => null,
		'data' => null,
	),
	'indexSquad' => array(
		'type' => 0,
		'description' => 'Просмотр всех бригад',
		'bizRule' => null,
		'data' => null,
	),
	'createSquad' => array(
		'type' => 0,
		'description' => 'Создание бригады',
		'bizRule' => null,
		'data' => null,
	),
	'updateSquad' => array(
		'type' => 0,
		'description' => 'Изменение бригады',
		'bizRule' => null,
		'data' => null,
	),
	'updateOwnSquad' => array(
		'type' => 1,
		'description' => 'Изменение бригады',
		'bizRule' => 'return Yii::app()->user->id == $params["squad"]->responsible_id;',
		'data' => null,
		'children' => array(
			0 => 'updateSquad',
		),
	),
	'indexAccounting' => array(
		'type' => 0,
		'description' => 'Просмотр всех сотрудников',
		'bizRule' => null,
		'data' => null,
	),
	'personalAccounting' => array(
		'type' => 0,
		'description' => 'Просмотр всех сотрудников (то же самое, что и в предыдущем случае)',
		'bizRule' => null,
		'data' => null,
	),
	'profileAccounting' => array(
		'type' => 0,
		'description' => 'Просмотр профиля пользователя',
		'bizRule' => null,
		'data' => null,
	),
	'changeUserPermissionsAccounting' => array(
		'type' => 0,
		'description' => 'Изменение прав доступа пользователя',
		'bizRule' => null,
		'data' => null,
	),
	'changeUserRoleAccounting' => array(
		'type' => 0,
		'description' => 'Изменение роли пользователя',
		'bizRule' => null,
		'data' => null,
	),
	'extendedChangeUserPermissionsAccounting' => array(
		'type' => 1,
		'description' => 'Полный контроль над правами доступа пользователя',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'changeUserPermissionsAccounting',
		),
	),
	'extendedChangeUserRoleAccounting' => array(
		'type' => 1,
		'description' => 'Полный контроль над изменением роли пользователя',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'changeUserRoleAccounting',
		),
	),
	'accessPartnersAdministration' => array(
		'type' => 0,
		'description' => 'Просмотр всех партнеров',
		'bizRule' => null,
		'data' => null,
	),
	'indexAdministration' => array(
		'type' => 0,
		'description' => 'Просмотр индекса администрации',
		'bizRule' => null,
		'data' => null,
	),
	'partnerActivityAdministration' => array(
		'type' => 0,
		'description' => 'Просмотр активности партнеров',
		'bizRule' => null,
		'data' => null,
	),
	'historyAdministration' => array(
		'type' => 0,
		'description' => 'Просмотр истории операций',
		'bizRule' => null,
		'data' => null,
	),
	'addPartnerAdministration' => array(
		'type' => 0,
		'description' => 'Добавить партнера',
		'bizRule' => null,
		'data' => null,
	),
	'updatePartnerAdministration' => array(
		'type' => 0,
		'description' => 'Обновление партнера',
		'bizRule' => null,
		'data' => null,
	),
	'indexCalendar' => array(
		'type' => 0,
		'description' => 'Просмотр календаря задач',
		'bizRule' => null,
		'data' => null,
	),
	'updateDateTaskCalendar' => array(
		'type' => 0,
		'description' => 'Перенос задачи на новую дату, используя календарь',
		'bizRule' => null,
		'data' => null,
	),
	'getEventsCalendar' => array(
		'type' => 0,
		'description' => 'Получение событий в календаре',
		'bizRule' => null,
		'data' => null,
	),
	'selectChaine' => array(
		'type' => 0,
		'description' => 'Выборка цепочек',
		'bizRule' => null,
		'data' => null,
	),
	'createChaine' => array(
		'type' => 0,
		'description' => 'Создать цепочку',
		'bizRule' => null,
		'data' => null,
	),
	'indexClients' => array(
		'type' => 0,
		'description' => 'Просмотр своих клиентов',
		'bizRule' => null,
		'data' => null,
	),
	'indexMyGroupClients' => array(
		'type' => 0,
		'description' => 'Просмотр клиентов своей группы (для руководителей групп продаж)',
		'bizRule' => null,
		'data' => null,
	),
	'indexAllClients' => array(
		'type' => 0,
		'description' => 'Просмотр всех клиентов',
		'bizRule' => null,
		'data' => null,
	),
	'appointResponsibleClients' => array(
		'type' => 0,
		'description' => 'Возможность назначать ответсвенного',
		'bizRule' => null,
		'data' => null,
	),
	'appointResponsibleFromAllClients' => array(
		'type' => 0,
		'description' => 'Возможность назначать ответсвенного, выбирая из всех',
		'bizRule' => null,
		'data' => null,
	),
	'addClients' => array(
		'type' => 0,
		'description' => 'Возможность создать нового клиента',
		'bizRule' => null,
		'data' => null,
	),
	'deleteClients' => array(
		'type' => 0,
		'description' => 'Возможность удалить клиента',
		'bizRule' => null,
		'data' => null,
	),
	'updateClients' => array(
		'type' => 0,
		'description' => 'Возможность обновлять данные клиента',
		'bizRule' => null,
		'data' => null,
	),
	'indexNews' => array(
		'type' => 0,
		'description' => 'Просмотр всех новостей',
		'bizRule' => null,
		'data' => null,
	),
	'editNews' => array(
		'type' => 0,
		'description' => 'Редактирование новостей',
		'bizRule' => null,
		'data' => null,
	),
	'createNews' => array(
		'type' => 0,
		'description' => 'Создание новости',
		'bizRule' => null,
		'data' => null,
	),
	'deleteNews' => array(
		'type' => 0,
		'description' => 'Удаление новости',
		'bizRule' => null,
		'data' => null,
	),
	'stabilityNetworkIt' => array(
		'type' => 0,
		'description' => 'Просмотр отчета по стабильности сети',
		'bizRule' => null,
		'data' => null,
	),
	'indexIt' => array(
		'type' => 0,
		'description' => 'Просмотр индекса контроллера ИТ',
		'bizRule' => null,
		'data' => null,
	),
	'mantisIt' => array(
		'type' => 0,
		'description' => 'Перенаправление на мантис',
		'bizRule' => null,
		'data' => null,
	),
	'jiraIt' => array(
		'type' => 0,
		'description' => 'Перенаправление на жиру',
		'bizRule' => null,
		'data' => null,
	),
	'viewModem' => array(
		'type' => 0,
		'description' => 'Просмотр модема',
		'bizRule' => null,
		'data' => null,
	),
	'createModem' => array(
		'type' => 0,
		'description' => 'Создание модема',
		'bizRule' => null,
		'data' => null,
	),
	'updateModem' => array(
		'type' => 0,
		'description' => 'Обновление модема',
		'bizRule' => null,
		'data' => null,
	),
	'deleteModem' => array(
		'type' => 0,
		'description' => 'Удаление модема',
		'bizRule' => null,
		'data' => null,
	),
	'indexModem' => array(
		'type' => 0,
		'description' => 'Просмотр списка модемов',
		'bizRule' => null,
		'data' => null,
	),
	'viewObj' => array(
		'type' => 0,
		'description' => 'Просмотр объекта',
		'bizRule' => null,
		'data' => null,
	),
	'createObj' => array(
		'type' => 0,
		'description' => 'Создание объекта',
		'bizRule' => null,
		'data' => null,
	),
	'deleteObj' => array(
		'type' => 0,
		'description' => 'Удаление объекта',
		'bizRule' => null,
		'data' => null,
	),
	'indexObj' => array(
		'type' => 0,
		'description' => 'Просмотр всех объектов',
		'bizRule' => null,
		'data' => null,
	),
	'worldMapObj' => array(
		'type' => 0,
		'description' => 'Просмотр всех объектов на карте',
		'bizRule' => null,
		'data' => null,
	),
	'changeTechParamsObj' => array(
		'type' => 0,
		'description' => 'Возможность изменять тех параметры объекта',
		'bizRule' => null,
		'data' => null,
	),
	'changeVolParamsObj' => array(
		'type' => 0,
		'description' => 'Возможность изменять громкость и время вещания объекта',
		'bizRule' => null,
		'data' => null,
	),
	'changePlayerParamsObj' => array(
		'type' => 0,
		'description' => 'Возможность изменять вкладку плеер объекта',
		'bizRule' => null,
		'data' => null,
	),
	'changeBroadcastOffParamsObj' => array(
		'type' => 0,
		'description' => 'Возможность изменять вкладку отключение эфира объекта',
		'bizRule' => null,
		'data' => null,
	),
	'historyObj' => array(
		'type' => 0,
		'description' => 'Возможность возможность просмотра истории объекта',
		'bizRule' => null,
		'data' => null,
	),
	'editObj' => array(
		'type' => 0,
		'description' => 'Возможность редактирования объекта',
		'bizRule' => null,
		'data' => null,
	),
	'changeStatusObj' => array(
		'type' => 0,
		'description' => 'Возможность изменения статуса объекта',
		'bizRule' => null,
		'data' => null,
	),
	'indexProvider' => array(
		'type' => 0,
		'description' => 'Просмотр всех провайдеров',
		'bizRule' => null,
		'data' => null,
	),
	'indexReport' => array(
		'type' => 0,
		'description' => 'Просмотр всех отчетов',
		'bizRule' => null,
		'data' => null,
	),
	'indexSales' => array(
		'type' => 0,
		'description' => 'Просмотр отчетов по продажам',
		'bizRule' => null,
		'data' => null,
	),
	'requestService' => array(
		'type' => 0,
		'description' => 'Просмотр заявок',
		'bizRule' => null,
		'data' => null,
	),
	'offTrackService' => array(
		'type' => 0,
		'description' => 'Отключение ролика',
		'bizRule' => null,
		'data' => null,
	),
	'deleteTrackService' => array(
		'type' => 0,
		'description' => 'Удаление ролика',
		'bizRule' => null,
		'data' => null,
	),
	'createRequestService' => array(
		'type' => 0,
		'description' => 'Создание заявки',
		'bizRule' => null,
		'data' => null,
	),
	'deleteRequestService' => array(
		'type' => 0,
		'description' => 'Удаление заявки',
		'bizRule' => null,
		'data' => null,
	),
	'closeRequestService' => array(
		'type' => 0,
		'description' => 'Закрытие заявки',
		'bizRule' => null,
		'data' => null,
	),
	'rollbackRequestService' => array(
		'type' => 0,
		'description' => 'Откатить заявку',
		'bizRule' => null,
		'data' => null,
	),
	'falseCallRequestService' => array(
		'type' => 0,
		'description' => 'Возможность пометить заявку как ложный вызов',
		'bizRule' => null,
		'data' => null,
	),
	'changeObjectRequestService' => array(
		'type' => 0,
		'description' => 'Возможность изменить объект в заявке',
		'bizRule' => null,
		'data' => null,
	),
	'manageRequestService' => array(
		'type' => 0,
		'description' => 'Управление заявкой',
		'bizRule' => null,
		'data' => null,
	),
	'indexAllRequestsService' => array(
		'type' => 0,
		'description' => 'Смотреть все заявки',
		'bizRule' => null,
		'data' => null,
	),
	'indexGrowRequestsService' => array(
		'type' => 0,
		'description' => 'Смотреть все заявки отдела развития',
		'bizRule' => null,
		'data' => null,
	),
	'indexTasks' => array(
		'type' => 0,
		'description' => 'Просмотр задач',
		'bizRule' => null,
		'data' => null,
	),
	'viewTasks' => array(
		'type' => 0,
		'description' => 'Просмотр задачи',
		'bizRule' => null,
		'data' => null,
	),
	'indexAllTasks' => array(
		'type' => 0,
		'description' => 'Просмотр всех задач',
		'bizRule' => null,
		'data' => null,
	),
	'indexMyGroupTasks' => array(
		'type' => 0,
		'description' => 'Просмотр задач своей группы',
		'bizRule' => null,
		'data' => null,
	),
	'addTasks' => array(
		'type' => 0,
		'description' => 'Добавление новой задачи',
		'bizRule' => null,
		'data' => null,
	),
	'deleteTasks' => array(
		'type' => 0,
		'description' => 'Удаление задачи',
		'bizRule' => null,
		'data' => null,
	),
	'updateTasks' => array(
		'type' => 0,
		'description' => 'Редактирование задачи',
		'bizRule' => null,
		'data' => null,
	),
	'appointResponsibleTasks' => array(
		'type' => 0,
		'description' => 'Возможность назначить ответственного по задаче',
		'bizRule' => null,
		'data' => null,
	),
	'closeTaskWithoutContactTasks' => array(
		'type' => 0,
		'description' => 'Возможность закрыть задачу без выбора контакта',
		'bizRule' => null,
		'data' => null,
	),
	'extendedUpdateTasks' => array(
		'type' => 0,
		'description' => 'Расширенное редактирование задачи (Возможность менять все параметры)',
		'bizRule' => null,
		'data' => null,
	),
	'indexTracks' => array(
		'type' => 0,
		'description' => 'Просмотр роликов',
		'bizRule' => null,
		'data' => null,
	),
	'createTrack' => array(
		'type' => 0,
		'description' => 'Добавление ролика',
		'bizRule' => null,
		'data' => null,
	),
	'editTrack' => array(
		'type' => 0,
		'description' => 'Редактирование ролика',
		'bizRule' => null,
		'data' => null,
	),
	'indexMediaplans' => array(
		'type' => 0,
		'description' => 'Просмотр медиапланов',
		'bizRule' => null,
		'data' => null,
	),
	'viewMediaplans' => array(
		'type' => 0,
		'description' => 'Просмотр карточки медиаплана',
		'bizRule' => null,
		'data' => null,
	),
	'updateMediaplans' => array(
		'type' => 0,
		'description' => 'Редактирование медиаплана',
		'bizRule' => null,
		'data' => null,
	),
	'createMediaplans' => array(
		'type' => 0,
		'description' => 'Создание медиаплана',
		'bizRule' => null,
		'data' => null,
	),
	'manageObjectGroupsMediaplans' => array(
		'type' => 0,
		'description' => 'Управление группировками объектов в медиаплане',
		'bizRule' => null,
		'data' => null,
	),
	'manageTracksMediaplans' => array(
		'type' => 0,
		'description' => 'Постановка роликов на эфир и прочее',
		'bizRule' => null,
		'data' => null,
	),
	'blocked' => array(
		'type' => 2,
		'description' => 'Заблокирован',
		'bizRule' => null,
		'data' => null,
	),
	'fired' => array(
		'type' => 2,
		'description' => 'Уволенный',
		'bizRule' => null,
		'data' => null,
	),
	'user' => array(
		'type' => 2,
		'description' => 'Пользователь системы',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'indexTracks',
		),
	),
	'objectObserver' => array(
		'type' => 1,
		'description' => 'Возможность просматривать объекты',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'indexObj',
			1 => 'worldMapObj',
			2 => 'viewObj',
		),
	),
	'accountingObserver' => array(
		'type' => 1,
		'description' => 'Возможность просматривать сотрудников',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'personalAccounting',
			1 => 'indexAccounting',
			2 => 'profileAccounting',
		),
	),
	'tasksManager' => array(
		'type' => 1,
		'description' => 'Возможность просматривать задачи',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'indexTasks',
			1 => 'addTasks',
			2 => 'deleteTasks',
			3 => 'updateTasks',
			4 => 'viewTasks',
		),
	),
	'clientsManager' => array(
		'type' => 1,
		'description' => 'Возможность просматривать клиентов',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'indexClients',
			1 => 'addClients',
			2 => 'updateClients',
		),
	),
	'calendarManager' => array(
		'type' => 1,
		'description' => 'Возможность просматривать календарь',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'indexCalendar',
			1 => 'updateDateTaskCalendar',
			2 => 'getEventsCalendar',
		),
	),
	'accountant' => array(
		'type' => 2,
		'description' => 'Бухгалтер',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'user',
			1 => 'accountingObserver',
		),
	),
	'accounting_head' => array(
		'type' => 2,
		'description' => 'Главный бухгалтер',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'accountant',
		),
	),
	'financial_head' => array(
		'type' => 2,
		'description' => 'Финансовый директор',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'accounting_head',
		),
	),
	'tech_support_employee' => array(
		'type' => 2,
		'description' => 'Сотрудник технической поддержки',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'user',
			1 => 'objectObserver',
			2 => 'requestService',
			3 => 'createRequestService',
			4 => 'indexSquad',
			5 => 'updateOwnSquad',
			6 => 'deleteRequestService',
			7 => 'rollbackRequestService',
			8 => 'changeObjectRequestService',
			9 => 'closeRequestService',
			10 => 'manageRequestService',
			11 => 'falseCallRequestService',
			12 => 'indexNews',
			13 => 'editNews',
			14 => 'deleteNews',
			15 => 'createNews',
		),
	),
	'tech_support_head' => array(
		'type' => 2,
		'description' => 'Глава группы технической поддержки',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'tech_support_employee',
			1 => 'viewModem',
			2 => 'createModem',
			3 => 'updateModem',
			4 => 'deleteModem',
			5 => 'indexModem',
			6 => 'indexProvider',
			7 => 'indexSquad',
			8 => 'createSquad',
			9 => 'updateSquad',
		),
	),
	'installation_employee' => array(
		'type' => 2,
		'description' => 'Монтажник',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'user',
			1 => 'objectObserver',
			2 => 'requestService',
			3 => 'createRequestService',
			4 => 'changeVolParamsObj',
			5 => 'changePlayerParamsObj',
		),
	),
	'installation_group_head' => array(
		'type' => 2,
		'description' => 'Глава группы монтажа',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'installation_employee',
		),
	),
	'driver' => array(
		'type' => 2,
		'description' => 'Водитель',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'user',
		),
	),
	'design_engineer' => array(
		'type' => 2,
		'description' => 'Инженер-конструктор',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'user',
			1 => 'objectObserver',
			2 => 'requestService',
			3 => 'createRequestService',
		),
	),
	'tech_head' => array(
		'type' => 2,
		'description' => 'Технический директор',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'installation_group_head',
			1 => 'tech_support_head',
			2 => 'driver',
			3 => 'design_engineer',
			4 => 'createObj',
			5 => 'deleteObj',
			6 => 'offTrackService',
			7 => 'deleteTrackService',
			8 => 'historyAdministration',
			9 => 'indexAdministration',
		),
	),
	'grow_employee' => array(
		'type' => 2,
		'description' => 'Сотрудник группы развития',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'user',
			1 => 'indexSales',
			2 => 'tasksManager',
			3 => 'clientsManager',
			4 => 'calendarManager',
			5 => 'requestService',
			6 => 'createRequestService',
			7 => 'deleteRequestService',
			8 => 'rollbackRequestService',
			9 => 'changeObjectRequestService',
			10 => 'closeRequestService',
			11 => 'manageRequestService',
			12 => 'accessPartnersAdministration',
			13 => 'indexAdministration',
			14 => 'partnerActivityAdministration',
			15 => 'historyAdministration',
			16 => 'addPartnerAdministration',
			17 => 'updatePartnerAdministration',
			18 => 'indexGrowRequestsService',
		),
	),
	'grow_group_head' => array(
		'type' => 2,
		'description' => 'Глава группы развития',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'grow_employee',
		),
	),
	'grow_head' => array(
		'type' => 2,
		'description' => 'Глава отдела развития',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'grow_group_head',
			1 => 'objectObserver',
			2 => 'accountingObserver',
			3 => 'createObj',
			4 => 'deleteObj',
			5 => 'historyAdministration',
			6 => 'indexAdministration',
		),
	),
	'sales_employee' => array(
		'type' => 2,
		'description' => 'Сотрудник группы продаж',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'user',
			1 => 'indexSales',
			2 => 'tasksManager',
			3 => 'clientsManager',
			4 => 'calendarManager',
			5 => 'objectObserver',
			6 => 'requestService',
			7 => 'createRequestService',
			8 => 'indexTracks',
			9 => 'indexMediaplans',
			10 => 'manageObjectGroupsMediaplans',
			11 => 'updateMediaplans',
			12 => 'createMediaplans',
		),
	),
	'sales_group_head' => array(
		'type' => 2,
		'description' => 'Глава группы продаж',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'sales_employee',
			1 => 'indexMyGroupClients',
			2 => 'appointResponsibleClients',
			3 => 'closeTaskWithoutContactTasks',
			4 => 'indexAllTasks',
			5 => 'indexMyGroupTasks',
			6 => 'appointResponsibleTasks',
		),
	),
	'monitoring_employee' => array(
		'type' => 2,
		'description' => 'Сотрудник группы мониторинга',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'user',
			1 => 'sales_employee',
			2 => 'indexMyGroupClients',
			3 => 'appointResponsibleClients',
			4 => 'appointResponsibleFromAllClients',
		),
	),
	'monitoring_group_head' => array(
		'type' => 2,
		'description' => 'Глава группы мониторинга',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'monitoring_employee',
			1 => 'deleteClients',
		),
	),
	'monitoring_head' => array(
		'type' => 2,
		'description' => 'Глава мониторинга',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'monitoring_group_head',
		),
	),
	'sales_supporter' => array(
		'type' => 2,
		'description' => 'Сотрудник группы поддержки продаж',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'user',
			1 => 'sales_employee',
			2 => 'indexAllClients',
		),
	),
	'sales_support_head' => array(
		'type' => 2,
		'description' => 'Глава группы поддержки продаж',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'sales_supporter',
		),
	),
	'sales_department_head' => array(
		'type' => 2,
		'description' => 'Глава отдела продаж',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'sales_group_head',
			1 => 'sales_support_head',
		),
	),
	'studio_employee' => array(
		'type' => 2,
		'description' => 'Сотрудник студии',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'user',
			1 => 'indexSales',
			2 => 'tasksManager',
			3 => 'clientsManager',
			4 => 'calendarManager',
			5 => 'createTrack',
			6 => 'editTrack',
			7 => 'indexTracks',
			8 => 'indexMediaplans',
			9 => 'viewMediaplans',
			10 => 'manageTracksMediaplans',
		),
	),
	'studio_head' => array(
		'type' => 2,
		'description' => 'Глава студии',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'studio_employee',
			1 => 'objectObserver',
			2 => 'accountingObserver',
			3 => 'createObj',
			4 => 'deleteObj',
			5 => 'historyAdministration',
			6 => 'indexAdministration',
		),
	),
	'sales_head' => array(
		'type' => 2,
		'description' => 'Коммерческий директор',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'sales_department_head',
			1 => 'monitoring_head',
			2 => 'studio_head',
			3 => 'grow_head',
		),
	),
	'manager' => array(
		'type' => 2,
		'description' => 'Менеджер',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'user',
			1 => 'objectObserver',
		),
	),
	'office_manager' => array(
		'type' => 2,
		'description' => 'Офис-менеджер',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'user',
			1 => 'objectObserver',
			2 => 'accountingObserver',
		),
	),
	'personal_manager' => array(
		'type' => 2,
		'description' => 'Менеджер по персоналу',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'user',
			1 => 'objectObserver',
			2 => 'accountingObserver',
		),
	),
	'administration_economy_employee' => array(
		'type' => 2,
		'description' => 'Хозяйственный сотрудник',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'user',
		),
	),
	'administration_economy_head' => array(
		'type' => 2,
		'description' => 'Директор',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'administration_economy_employee',
		),
	),
	'executive_director' => array(
		'type' => 2,
		'description' => 'Исполнительный директор',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'manager',
			1 => 'office_manager',
			2 => 'personal_manager',
			3 => 'administration_economy_head',
		),
	),
	'system_administrator' => array(
		'type' => 2,
		'description' => 'Системный администратор',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'user',
			1 => 'objectObserver',
			2 => 'accountingObserver',
			3 => 'requestService',
			4 => 'createRequestService',
			5 => 'indexProvider',
			6 => 'stabilityNetworkIt',
			7 => 'indexIt',
			8 => 'viewModem',
			9 => 'createModem',
			10 => 'updateModem',
			11 => 'deleteModem',
			12 => 'indexModem',
			13 => 'mantisIt',
			14 => 'jiraIt',
			15 => 'indexSquad',
			16 => 'createSquad',
			17 => 'updateSquad',
			18 => 'changeTechParamsObj',
			19 => 'changeVolParamsObj',
			20 => 'changePlayerParamsObj',
			21 => 'changeBroadcastOffParamsObj',
			22 => 'historyObj',
			23 => 'editObj',
			24 => 'changeStatusObj',
		),
	),
	'system_adm_group_head' => array(
		'type' => 2,
		'description' => 'Руководитель группы системного администрирования',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'system_administrator',
		),
	),
	'system_adm_head' => array(
		'type' => 2,
		'description' => 'Руководитель системного администрирования',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'system_adm_group_head',
		),
	),
	'1c_developer' => array(
		'type' => 2,
		'description' => '1C программист',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'user',
			1 => 'objectObserver',
			2 => 'accountingObserver',
			3 => 'indexSales',
			4 => 'clientsManager',
			5 => 'tasksManager',
			6 => 'mantisIt',
			7 => 'indexIt',
			8 => 'jiraIt',
		),
	),
	'1c_dev_head' => array(
		'type' => 2,
		'description' => 'Руководитель группы 1C разработки',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => '1c_developer',
			1 => 'historyAdministration',
			2 => 'requestService',
		),
	),
	'po_developer' => array(
		'type' => 2,
		'description' => 'C++ программист',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'user',
			1 => 'objectObserver',
			2 => 'createObj',
			3 => 'deleteObj',
			4 => 'offTrackService',
			5 => 'deleteTrackService',
			6 => 'requestService',
			7 => 'createRequestService',
			8 => 'mantisIt',
			9 => 'jiraIt',
		),
	),
	'po_dev_group_head' => array(
		'type' => 2,
		'description' => 'Руководитель группы C++ разработки',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'po_developer',
		),
	),
	'po_dev_head' => array(
		'type' => 2,
		'description' => 'Руководитель C++ разработки',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'po_dev_group_head',
		),
	),
	'tester' => array(
		'type' => 2,
		'description' => 'Тестер',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'user',
			1 => 'objectObserver',
			2 => 'requestService',
			3 => 'createRequestService',
			4 => 'mantisIt',
			5 => 'jiraIt',
		),
	),
	'testers_group_head' => array(
		'type' => 2,
		'description' => 'Руководитель группы тестирования',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'tester',
		),
	),
	'testers_head' => array(
		'type' => 2,
		'description' => 'Руководитель тестирования',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'testers_group_head',
		),
	),
	'it_head' => array(
		'type' => 2,
		'description' => 'It-директор',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => '1c_dev_head',
			1 => 'po_dev_head',
			2 => 'system_adm_head',
			3 => 'testers_head',
		),
	),
	'sys_admin' => array(
		'type' => 2,
		'description' => 'Администратор ERP системы',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'financial_head',
			1 => 'tech_head',
			2 => 'grow_head',
			3 => 'sales_head',
			4 => 'executive_director',
			5 => 'it_head',
			6 => 'mantisIt',
			7 => 'jiraIt',
		),
	),
	'general' => array(
		'type' => 2,
		'description' => 'Генеральный директор',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'sys_admin',
		),
	),
	'admin' => array(
		'type' => 2,
		'description' => 'Да Убоятся Смертные Гнева Его Ибо Он Есть Господь',
		'bizRule' => null,
		'data' => null,
		'children' => array(
			0 => 'general',
			1 => 'reinstallRbacTest',
			2 => 'panelTest',
			3 => 'extendedChangeUserPermissionsAccounting',
			4 => 'extendedChangeUserRoleAccounting',
			5 => 'extendedUpdateTasks',
		),
	),
);
